script: bacon -q -Ilib -I. test/*_test.rb
before_install: bundle init --gemspec=.gemspec
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- jruby-18mode
# enable when jruby-19 + bacon bug resolved
# - jruby-19mode
- rbx
